<?php
$title = 'Edit album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php 
$form=$this->form;


$form->setAttribute('action', $this->url('album',array('action'=>'edit', 'id'=>$this->id)));

echo $this->form()->openTag($form) ;

?>

<dl class="zend_form">
     
    <?php echo $this->formInput($form->get('id')) ?>
    <dt>
    <?php echo $this->formLabel($form->get('title')) ?>
    </dt>
    <dd>
         <?php echo $this->formInput($form->get('title')) ?>
         <?php echo $this->formElementErrors($form->get('title')) ?>
    </dd>
    
    <dt>
    <?php echo $this->formLabel($form->get('artist')) ?>
    </dt>
     <dd>
         <?php echo $this->formInput($form->get('artist')) ?>
         <?php echo $this->formElementErrors($form->get('artist')) ?>
    </dd>
    
     <dd>
         <?php echo $this->formInput($form->get('submit')) ?>
         <?php echo $this->formElementErrors($form->get('submit')) ?>
    </dd>
    
</dl>
<?
    echo $this->form()->closetag($form);
?>